export interface ResumeTheme {
  id: string;
  name: string;
  description: string;
  headerStyle: string;
  sectionTitleStyle: string;
  bodyStyle: string;
  accentColor: string;
  fontFamily: string;
  premium?: boolean;
}

export const resumeThemes: ResumeTheme[] = [
  {
    id: 'classic',
    name: '클래식',
    description: '전통적인 이력서',
    headerStyle: 'border-b-2 border-slate-800 pb-6 mb-8',
    sectionTitleStyle: 'text-sm font-bold text-slate-800 uppercase tracking-widest border-b border-slate-300 pb-1.5 mb-3',
    bodyStyle: 'text-slate-800',
    accentColor: 'slate',
    fontFamily: "-apple-system, 'Pretendard', 'Noto Sans KR', sans-serif",
  },
  {
    id: 'modern',
    name: '모던',
    description: '좌측 악센트 바',
    headerStyle: 'border-l-[6px] border-blue-600 pl-6 pb-6 mb-8',
    sectionTitleStyle: 'text-sm font-bold text-blue-700 mb-3 pl-3 border-l-[3px] border-blue-400',
    bodyStyle: 'text-slate-700',
    accentColor: 'blue',
    fontFamily: "'Inter', -apple-system, sans-serif",
  },
  {
    id: 'minimal',
    name: '미니멀',
    description: '극도로 심플한',
    headerStyle: 'pb-3 mb-6',
    sectionTitleStyle: 'text-[10px] font-medium text-slate-400 uppercase tracking-[0.4em] mb-4 pb-1',
    bodyStyle: 'text-slate-500',
    accentColor: 'slate',
    fontFamily: "'Helvetica Neue', -apple-system, sans-serif",
  },
  {
    id: 'professional',
    name: '프로페셔널',
    description: '다크 헤더 포멀',
    headerStyle: 'bg-slate-900 text-white -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-8 sm:pt-10 pb-8 mb-8',
    sectionTitleStyle: 'text-sm font-bold text-white bg-slate-800 -mx-2 px-3 py-1.5 mb-3 rounded',
    bodyStyle: 'text-slate-700',
    accentColor: 'slate',
    fontFamily: "'Noto Sans KR', sans-serif",
    premium: true,
  },
  {
    id: 'creative',
    name: '크리에이티브',
    description: '그라디언트 컬러풀',
    headerStyle: 'bg-gradient-to-r from-purple-600 via-pink-500 to-orange-400 text-white -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-10 sm:pt-12 pb-10 mb-8 rounded-b-3xl',
    sectionTitleStyle: 'text-sm font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-pink-500 uppercase tracking-wider mb-3',
    bodyStyle: 'text-slate-700',
    accentColor: 'purple',
    fontFamily: "'Pretendard', sans-serif",
    premium: true,
  },
  {
    id: 'executive',
    name: '임원급',
    description: '세리프 격식체',
    headerStyle: 'text-center pb-8 mb-10 border-b border-double border-slate-400',
    sectionTitleStyle: 'text-center text-xs font-normal text-slate-600 uppercase tracking-[0.4em] mb-4 border-b border-t border-slate-200 py-2',
    bodyStyle: 'text-slate-700 leading-relaxed',
    accentColor: 'slate',
    fontFamily: "'Georgia', 'Noto Serif KR', serif",
    premium: true,
  },
  {
    id: 'startup',
    name: '스타트업',
    description: '인디고 그라디언트',
    headerStyle: 'bg-gradient-to-br from-indigo-600 to-cyan-500 text-white -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-8 sm:pt-10 pb-8 mb-8',
    sectionTitleStyle: 'text-sm font-bold text-indigo-600 mb-3 flex items-center gap-2 before:content-[""] before:w-10 before:h-[2px] before:bg-gradient-to-r before:from-indigo-500 before:to-cyan-400',
    bodyStyle: 'text-slate-700',
    accentColor: 'indigo',
    fontFamily: "'Inter', -apple-system, sans-serif",
    premium: true,
  },
  {
    id: 'academic',
    name: '학술',
    description: '논문 스타일',
    headerStyle: 'border-b border-slate-400 pb-4 mb-6',
    sectionTitleStyle: 'text-[13px] font-bold text-slate-900 mb-2 pb-0.5 border-b-[3px] border-slate-900 inline-block pr-8',
    bodyStyle: 'text-slate-800 leading-[1.8]',
    accentColor: 'slate',
    fontFamily: "'Times New Roman', 'Noto Serif KR', serif",
    premium: true,
  },
  {
    id: 'tech',
    name: '테크',
    description: '터미널 다크',
    headerStyle: 'bg-[#0d1117] text-[#58a6ff] -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-6 sm:pt-10 pb-6 mb-8 font-mono border-b-2 border-[#30363d]',
    sectionTitleStyle: 'text-xs font-bold text-[#7ee787] font-mono uppercase tracking-wider mb-3 before:content-["$"] before:text-[#484f58] before:mr-2',
    bodyStyle: 'text-slate-700',
    accentColor: 'green',
    fontFamily: "'JetBrains Mono', 'Fira Code', 'D2Coding', monospace",
    premium: true,
  },
  {
    id: 'elegant',
    name: '엘레강트',
    description: '골드 럭셔리',
    headerStyle: 'text-center pb-8 mb-8 border-b-2 border-amber-400',
    sectionTitleStyle: 'text-center text-[11px] font-light text-amber-700 uppercase tracking-[0.4em] mb-4 pb-2 border-b border-amber-200',
    bodyStyle: 'text-slate-700',
    accentColor: 'amber',
    fontFamily: "'Playfair Display', 'Noto Serif KR', serif",
    premium: true,
  },
  {
    id: 'newspaper',
    name: '뉴스페이퍼',
    description: '신문 칼럼 스타일',
    headerStyle: 'text-center border-y-4 border-double border-slate-900 py-4 mb-6',
    sectionTitleStyle: 'text-center text-xs font-black text-slate-900 uppercase tracking-[0.25em] mb-3 py-1 border-y border-slate-300',
    bodyStyle: 'text-slate-800 leading-relaxed',
    accentColor: 'slate',
    fontFamily: "'Georgia', 'Noto Serif KR', serif",
    premium: true,
  },
  {
    id: 'pastel',
    name: '파스텔',
    description: '부드러운 파스텔',
    headerStyle: 'bg-gradient-to-r from-pink-100 via-purple-100 to-blue-100 -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-8 sm:pt-10 pb-8 mb-8 rounded-b-[2rem]',
    sectionTitleStyle: 'text-sm font-semibold text-purple-500 mb-3 flex items-center gap-2 before:content-[""] before:w-3 before:h-3 before:bg-gradient-to-br before:from-pink-400 before:to-purple-400 before:rounded-full',
    bodyStyle: 'text-slate-600',
    accentColor: 'purple',
    fontFamily: "'Pretendard', -apple-system, sans-serif",
    premium: true,
  },
  {
    id: 'dark',
    name: '다크',
    description: '다크 모던',
    headerStyle: 'bg-[#1a1a2e] text-[#e0e0e0] -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-8 sm:pt-10 pb-8 mb-8',
    sectionTitleStyle: 'text-sm font-bold text-[#6c63ff] uppercase tracking-wider mb-3 border-l-4 border-[#6c63ff] pl-3',
    bodyStyle: 'text-slate-700',
    accentColor: 'slate',
    fontFamily: "'Inter', -apple-system, sans-serif",
    premium: true,
  },
  {
    id: 'corporate',
    name: '대기업',
    description: '공채 최적화',
    headerStyle: 'border-b-2 border-slate-800 pb-6 mb-8',
    sectionTitleStyle: 'text-xs font-bold text-white bg-slate-900 -mx-1 px-3 py-2 mb-3',
    bodyStyle: 'text-slate-800',
    accentColor: 'slate',
    fontFamily: "'Noto Sans KR', sans-serif",
    premium: true,
  },
  {
    id: 'portfolio',
    name: '포트폴리오',
    description: '크리에이터 전용',
    headerStyle: 'bg-gradient-to-br from-indigo-700 via-purple-600 to-pink-500 text-white -mx-6 sm:-mx-10 -mt-6 sm:-mt-10 px-6 sm:px-10 pt-12 sm:pt-14 pb-12 mb-8',
    sectionTitleStyle: 'text-lg font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 via-purple-500 to-pink-500 mb-4',
    bodyStyle: 'text-slate-700',
    accentColor: 'indigo',
    fontFamily: "'Pretendard', sans-serif",
    premium: true,
  },
];
