import { Controller, Post, Body, Req } from '@nestjs/common';
import { ApiTags, ApiOperation } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';
import { LlmService } from './llm.service';
import { ResumesService } from '../resumes/resumes.service';
import { AutoGenerateDto } from './dto/auto-generate.dto';

@ApiTags('auto-generate')
@Controller('auto-generate')
export class AutoGenerateController {
  constructor(
    private readonly llmService: LlmService,
    private readonly resumesService: ResumesService,
  ) {}

  @Post('preview')
  @ApiOperation({ summary: '비정형 텍스트로 이력서 미리보기 (저장 안 함)' })
  @Throttle({ default: { limit: 5, ttl: 60000 } })
  async preview(@Body() dto: AutoGenerateDto) {
    return this.llmService.autoGenerate(dto.rawText, dto.instruction);
  }

  @Post('create')
  @ApiOperation({ summary: '비정형 텍스트로 이력서 자동 생성 + DB 저장' })
  @Throttle({ default: { limit: 5, ttl: 60000 } })
  async create(@Body() dto: AutoGenerateDto, @Req() req: any) {
    const { resume, tokensUsed, provider, model } = await this.llmService.autoGenerate(
      dto.rawText,
      dto.instruction,
    );

    // DB에 저장
    const saved = await this.resumesService.create(resume, req.user?.id);

    return {
      resume: saved,
      tokensUsed,
      provider,
      model,
    };
  }
}
