import { Controller, Post, Body, Req, UploadedFile, UseInterceptors } from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { ApiTags, ApiOperation } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';
import { LlmService } from './llm.service';
import { FileTextExtractorService } from './file-text-extractor.service';
import { ResumesService } from '../resumes/resumes.service';
import { AutoGenerateDto } from './dto/auto-generate.dto';

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

@ApiTags('auto-generate')
@Controller('auto-generate')
export class AutoGenerateController {
  constructor(
    private readonly llmService: LlmService,
    private readonly resumesService: ResumesService,
    private readonly fileExtractor: FileTextExtractorService,
  ) {}

  @Post('preview')
  @ApiOperation({ summary: '비정형 텍스트/PDF/DOCX 로 이력서 미리보기 (저장 안 함)' })
  @Throttle({ default: { limit: 5, ttl: 60000 } })
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_FILE_SIZE } }))
  async preview(@Body() dto: AutoGenerateDto, @UploadedFile() file?: Express.Multer.File) {
    const rawText = file ? await this.fileExtractor.extract(file) : dto.rawText;
    return this.llmService.autoGenerate(rawText, dto.instruction);
  }

  @Post('create')
  @ApiOperation({ summary: '비정형 텍스트/PDF/DOCX 로 이력서 자동 생성 + DB 저장' })
  @Throttle({ default: { limit: 5, ttl: 60000 } })
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_FILE_SIZE } }))
  async create(
    @Body() dto: AutoGenerateDto,
    @Req() req: any,
    @UploadedFile() file?: Express.Multer.File,
  ) {
    const rawText = file ? await this.fileExtractor.extract(file) : dto.rawText;
    const { resume, tokensUsed, provider, model } = await this.llmService.autoGenerate(
      rawText,
      dto.instruction,
    );

    // DB에 저장
    const saved = await this.resumesService.create(resume, req.user?.id);

    return {
      resume: saved,
      tokensUsed,
      provider,
      model,
    };
  }
}
