import { createZodDto } from 'nestjs-zod'
import { z } from 'zod'

export const autoGenerateSchema = z
  .object({
    rawText: z
      .string()
      .min(10, '텍스트는 최소 10자 이상이어야 합니다')
      .max(15000, '텍스트는 15000자 이내여야 합니다'),
    instruction: z.string().max(500, '지시사항은 500자 이내여야 합니다').optional(),
    templateId: z.string().max(100).optional(),
    provider: z.string().max(50).optional(),
  })
  .strict()
export class AutoGenerateDto extends createZodDto(autoGenerateSchema) {}

export const enhanceWithDocumentSchema = z
  .object({
    documentText: z
      .string()
      .min(30, '최소 30자 이상의 문서 텍스트가 필요합니다')
      .max(15000, '문서는 15000자 이내여야 합니다'),
    instruction: z.string().max(500).optional(),
    provider: z.string().max(50).optional(),
  })
  .strict()
export class EnhanceWithDocumentDto extends createZodDto(enhanceWithDocumentSchema) {}
