"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "AutoGenerateDto", {
    enumerable: true,
    get: function() {
        return AutoGenerateDto;
    }
});
const _swagger = require("@nestjs/swagger");
const _classvalidator = require("class-validator");
function _ts_decorate(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for(var i = decorators.length - 1; i >= 0; i--)if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
}
function _ts_metadata(k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
}
let AutoGenerateDto = class AutoGenerateDto {
};
_ts_decorate([
    (0, _swagger.ApiProperty)({
        description: '경력 관련 원본 텍스트 (메모, LinkedIn 복사, 이전 이력서 등 자유 형식)'
    }),
    (0, _classvalidator.IsString)(),
    (0, _classvalidator.MinLength)(10, {
        message: '텍스트는 최소 10자 이상이어야 합니다'
    }),
    (0, _classvalidator.MaxLength)(15000, {
        message: '텍스트는 15000자 이내여야 합니다'
    }),
    _ts_metadata("design:type", String)
], AutoGenerateDto.prototype, "rawText", void 0);
_ts_decorate([
    (0, _swagger.ApiPropertyOptional)({
        description: '추가 지시사항 (예: 개발자 이력서로 만들어줘)'
    }),
    (0, _classvalidator.IsOptional)(),
    (0, _classvalidator.IsString)(),
    (0, _classvalidator.MaxLength)(500, {
        message: '지시사항은 500자 이내여야 합니다'
    }),
    _ts_metadata("design:type", String)
], AutoGenerateDto.prototype, "instruction", void 0);
