import { LlmService } from './llm.service';
import { ResumesService } from '../resumes/resumes.service';
import { AutoGenerateDto } from './dto/auto-generate.dto';
export declare class AutoGenerateController {
    private readonly llmService;
    private readonly resumesService;
    constructor(llmService: LlmService, resumesService: ResumesService);
    preview(dto: AutoGenerateDto): Promise<{
        resume: any;
        tokensUsed: number;
        provider: string;
        model: string;
    }>;
    create(dto: AutoGenerateDto, req: any): Promise<{
        resume: {
            experiences: {
                [k: string]: any;
            }[];
            educations: {
                [k: string]: any;
            }[];
            skills: {
                [k: string]: any;
            }[];
            projects: {
                [k: string]: any;
            }[];
            certifications: {
                [k: string]: any;
            }[];
            languages: {
                [k: string]: any;
            }[];
            awards: {
                [k: string]: any;
            }[];
            activities: {
                [k: string]: any;
            }[];
            id: any;
            title: any;
            slug: any;
            userId: any;
            viewCount: any;
            visibility: any;
            personalInfo: {
                name: any;
                email: any;
                phone: any;
                address: any;
                website: any;
                github: any;
                summary: any;
                photo: any;
                birthYear: any;
                links: any;
                military: any;
            };
            tags: any;
            createdAt: any;
            updatedAt: any;
        };
        tokensUsed: number;
        provider: string;
        model: string;
    }>;
}
