import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsOptional } from 'class-validator';

export class AutoGenerateDto {
  @ApiProperty({ description: '경력 관련 원본 텍스트 (메모, LinkedIn 복사, 이전 이력서 등 자유 형식)' })
  @IsString()
  rawText!: string;

  @ApiPropertyOptional({ description: '추가 지시사항 (예: 개발자 이력서로 만들어줘)' })
  @IsOptional()
  @IsString()
  instruction?: string;
}
