import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsOptional, MaxLength, MinLength } from 'class-validator';

export class AutoGenerateDto {
  @ApiProperty({ description: '경력 관련 원본 텍스트 (메모, LinkedIn 복사, 이전 이력서 등 자유 형식)' })
  @IsString()
  @MinLength(10, { message: '텍스트는 최소 10자 이상이어야 합니다' })
  @MaxLength(15000, { message: '텍스트는 15000자 이내여야 합니다' })
  rawText!: string;

  @ApiPropertyOptional({ description: '추가 지시사항 (예: 개발자 이력서로 만들어줘)' })
  @IsOptional()
  @IsString()
  @MaxLength(500, { message: '지시사항은 500자 이내여야 합니다' })
  instruction?: string;
}
