import { PrismaService } from '../prisma/prisma.service';
import { SystemConfigService } from '../system-config/system-config.service';
export declare class JobsService {
    private prisma;
    private config;
    constructor(prisma: PrismaService, config: SystemConfigService);
    findAll(status?: string, query?: string): Promise<({
        user: {
            id: string;
            name: string;
            avatar: string;
            companyName: string | null;
        };
    } & {
        id: string;
        userId: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        description: string;
        requirements: string;
        benefits: string;
        type: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
    })[]>;
    findOne(id: string): Promise<{
        user: {
            id: string;
            email: string;
            name: string;
            avatar: string;
            companyName: string | null;
        };
    } & {
        id: string;
        userId: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        description: string;
        requirements: string;
        benefits: string;
        type: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    findByUser(userId: string): Promise<{
        id: string;
        userId: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        description: string;
        requirements: string;
        benefits: string;
        type: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    create(userId: string, data: any): Promise<{
        id: string;
        userId: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        description: string;
        requirements: string;
        benefits: string;
        type: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(id: string, userId: string, data: any): Promise<{
        id: string;
        userId: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        description: string;
        requirements: string;
        benefits: string;
        type: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    remove(id: string, userId: string, role?: string): Promise<{
        success: boolean;
    }>;
    getExternalLinks(filters: {
        category?: string;
        companySize?: string;
        careerLevel?: string;
        jobType?: string;
        location?: string;
        jobCategory?: string;
        q?: string;
    }): Promise<{
        id: string;
        location: string;
        description: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        url: string;
        logoEmoji: string;
        logoUrl: string;
        badgeText: string;
        gradientFrom: string;
        gradientTo: string;
        matchKeywords: string;
        category: string;
        companySize: string;
        jobTypes: string;
        careerLevel: string;
        jobCategory: string;
        isActive: boolean;
        order: number;
        clickCount: number;
    }[]>;
    recordExternalLinkClick(id: string): Promise<{
        url: string;
    }>;
    createExternalLink(data: any, user: {
        id?: string;
        role?: string;
        userType?: string;
    }): Promise<{
        id: string;
        location: string;
        description: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        url: string;
        logoEmoji: string;
        logoUrl: string;
        badgeText: string;
        gradientFrom: string;
        gradientTo: string;
        matchKeywords: string;
        category: string;
        companySize: string;
        jobTypes: string;
        careerLevel: string;
        jobCategory: string;
        isActive: boolean;
        order: number;
        clickCount: number;
    }>;
    updateExternalLink(id: string, data: any, user: {
        id?: string;
        role?: string;
        userType?: string;
    }): Promise<{
        id: string;
        location: string;
        description: string;
        createdAt: Date;
        updatedAt: Date;
        name: string;
        url: string;
        logoEmoji: string;
        logoUrl: string;
        badgeText: string;
        gradientFrom: string;
        gradientTo: string;
        matchKeywords: string;
        category: string;
        companySize: string;
        jobTypes: string;
        careerLevel: string;
        jobCategory: string;
        isActive: boolean;
        order: number;
        clickCount: number;
    }>;
    deleteExternalLink(id: string, user: {
        id?: string;
        role?: string;
        userType?: string;
    }): Promise<{
        success: boolean;
    }>;
    getCuratedJobs(filters: {
        jobType?: string;
        experienceLevel?: string;
        companySize?: string;
        industry?: string;
        location?: string;
        q?: string;
        page?: number;
        limit?: number;
    }): Promise<{
        items: ({
            author: {
                id: string;
                name: string;
                companyName: string | null;
            } | null;
        } & {
            id: string;
            company: string;
            position: string;
            location: string;
            salary: string;
            requirements: string;
            benefits: string;
            status: string;
            skills: string;
            createdAt: Date;
            updatedAt: Date;
            companySize: string;
            clickCount: number;
            companyLogo: string;
            department: string;
            summary: string;
            jobType: string;
            experienceLevel: string;
            education: string;
            industry: string;
            sourceUrl: string;
            sourceSite: string;
            deadline: Date | null;
            isRolling: boolean;
            viewCount: number;
            authorId: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
        totalPages: number;
    }>;
    getCuratedJob(id: string): Promise<{
        author: {
            id: string;
            name: string;
            companyName: string | null;
        } | null;
    } & {
        id: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        requirements: string;
        benefits: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
        companySize: string;
        clickCount: number;
        companyLogo: string;
        department: string;
        summary: string;
        jobType: string;
        experienceLevel: string;
        education: string;
        industry: string;
        sourceUrl: string;
        sourceSite: string;
        deadline: Date | null;
        isRolling: boolean;
        viewCount: number;
        authorId: string | null;
    }>;
    createCuratedJob(data: any, userId: string, userRole: string, userType: string): Promise<{
        id: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        requirements: string;
        benefits: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
        companySize: string;
        clickCount: number;
        companyLogo: string;
        department: string;
        summary: string;
        jobType: string;
        experienceLevel: string;
        education: string;
        industry: string;
        sourceUrl: string;
        sourceSite: string;
        deadline: Date | null;
        isRolling: boolean;
        viewCount: number;
        authorId: string | null;
    }>;
    updateCuratedJob(id: string, data: any, userId: string, userRole: string, userType?: string): Promise<{
        id: string;
        company: string;
        position: string;
        location: string;
        salary: string;
        requirements: string;
        benefits: string;
        status: string;
        skills: string;
        createdAt: Date;
        updatedAt: Date;
        companySize: string;
        clickCount: number;
        companyLogo: string;
        department: string;
        summary: string;
        jobType: string;
        experienceLevel: string;
        education: string;
        industry: string;
        sourceUrl: string;
        sourceSite: string;
        deadline: Date | null;
        isRolling: boolean;
        viewCount: number;
        authorId: string | null;
    }>;
    deleteCuratedJob(id: string, userId: string, userRole: string, userType?: string): Promise<{
        success: boolean;
    }>;
    recordCuratedJobClick(id: string): Promise<{
        sourceUrl: string;
    }>;
}
